[package]
name = "fbbe"
description = "Fast Bitcoin Block Explorer"
version = "0.1.1"
edition = "2021"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
license = "MIT"
repository = "https://github.com/RCasatta/fbbe"

[dependencies]
hyper = { version = "0.14.23", features = ["full"] }
tokio = { version = "1.21.2", features = ["full"] }
futures = "0.3"
futures-util = { version = "0.3", default-features = false }
serde =  { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
once_cell = "1.16.0"
#bitcoin = { version = "0.29.2", features = ["serde"] }
maud = "0.24.0"
bitcoin_hashes = "0.11.0"
env_logger = "0.10.0"
bitcoin = { version="0.29.2", features = ["serde"] }
log = "0.4.17"
lru = "0.8.1"
chrono = "0.4.23"
thousands = "0.2.0"
timeago = "0.3.1"
structopt = "0.3.26"
html2text = "0.4.4"
mime = "0.3.16"
